/*
g++-15 -std=c++23 -fmodules-ts -fsearch-include-path bits/std.cc -o
AirlineTicket AirlineTicket.cpp AirlineTicketTest.cpp AirlineTicket.o
*/

/*
alternative:
g++-15 -std=c++23 -fmodules-ts  -o AirlineTicket AirlineTicket.cpp
AirlineTicketTest.cpp AirlineTicket.o std.o

std.o will be generated by the compilation command in cppm.

*/

import airline_ticket;

import std;

using namespace std;
int main() {
  AirlineTicket myTicket;

  myTicket.setPassengerName("Sherman T. Socketwrench");
  myTicket.setNumberOfMiles(700);
  double cost{myTicket.calculatePriceInDollars()};
  println("This is the ticket for {}", myTicket.getPassengerName());
  println("and the cost is ${}", cost);
}